### ISSUE TITLE
Beta134

### ISSUE THREAD

**Issue by Eden790** [MicrosoftDocs/typography-issues#1163]
### Description

Wilfks
@
### Page URL

https://github.com/MicrosoftDocs/typography-issues/issues/new?assignees=&labels=OpenType+spec&projects=&template=opentype-docs-feedback.ym

### Content source URL

https://github.com/MicrosoftDocs/typography-issues/issues/new?assignees=&labels=OpenType+spec&projects=&template=opentype-docs-feedback.yl
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/typography-issues/issues/1161
- [ ] https://github.com/MicrosoftDocs/typography-issues/issues/1162
- [x] https://github.com/MicrosoftDocs/typography-issues/issu
- [ ] https://github.com/MicrosoftDocs/typography-issues/issues/1160
```

**Comment by PeterCon** [comment]
No actional feedback, so closing.
